# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: ru
pipeline: "supervised_embeddings"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: KerasPolicy
    epochs: 200
    max_history: 4
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
    nlu_threshold: 0.3
    core_threshold: 0.3
  - name: MemoizationPolicy
    max_history: 4
  - name: FormPolicy